import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import type { Metadata } from "next";
import type { ReactElement, ReactNode } from "react";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "@/theme";
import { PageContainer } from "@/components/layout/PageContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: ReactNode;
  modal: ReactNode;
}>): ReactElement {
  return (
    <html lang="en" className={"h-full w-full"}>
      <head>
        <title>Default title</title>
        <ColorSchemeScript defaultColorScheme={"auto"} />
      </head>

      <body className={"h-full w-full"}>
        <MantineProvider theme={theme}>
          <PageContainer>{children}</PageContainer>
          <div>{modal}</div>
        </MantineProvider>
      </body>
    </html>
  );
}
